module.exports = {
  WAITING_TITLE: 'WAITING_TITLE',
  WAITING_DESCRIPTION: 'WAITING_DESCRIPTION',
  WAITING_PHOTO: 'WAITING_PHOTO',
  WAITING_PRICE: 'WAITING_PRICE',
  WAITING_QUANTITY: 'WAITING_QUANTITY',
  WAITING_CONFIRMATION: 'WAITING_CONFIRMATION'
};
