module.exports = {
  WAITING_NAME: 'WAITING_NAME',
  WAITING_LOCATION_TYPE: 'WAITING_LOCATION_TYPE',
  WAITING_LOUNGE: 'WAITING_LOUNGE',
  WAITING_RESTAURANT_TABLE: 'WAITING_RESTAURANT_TABLE',
  COMPLETED: 'COMPLETED'
};
